#sonar.projectName=sunbird-telemetry-sdk
#sonar.language=js
#sonar.sources=.
#sonar.projectKey=project-sunbird_sunbird-telemetry-sdk
#sonar.host.url=https://sonarcloud.io
#sonar.organization=project-sunbird
#sonar.projectVersion=1.0 
